apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: movieguru
spec:
{{- if .Values.deployFull }}
  replicas: 0
{{-  end }}
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: redis:6.2-alpine
          args: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: movieguru
spec:
  selector:
    app: cache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cache
  namespace: movieguru
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cache
  minReplicas: {{ .Values.Cache.minReplicas }}
  maxReplicas: 25
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cache-pdb
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: cache