# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flows
  namespace: movieguru
spec:
  replicas: {{ .Values. Flows.replicas }}
  selector:
    matchLabels:
      app: flows
  template:
    metadata:
      labels:
        app: flows
    spec:
      serviceAccountName: movieguru-sa
      containers:
        - name: flows
          image: "{{ .Values.region }}-docker.pkg.dev/{{ .Values.projectID }}/movie-guru/flows:{{ .Values.Image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3400
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "750m"
              memory: "2Gi"            
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.Hosts.postgres }}
              value: {{ .Values.projectID }}
            - name: POSTGRES_DB_USER_PASSWORD
              value: "minimal"
            - name: POSTGRES_DB_USER
              value: "minimal-user"
            - name: TABLE_NAME
              value: "movies"
            - name: POSTGRES_DB_NAME
              value: "fake-movies-db"
            - name: LOCATION
              value: {{ .Values.Flows.modelLocation }}
            - name: USEGEMINIFLASH2
              value: {{ .Values.Flows.geminiflash2 }}

---
apiVersion: v1
kind: Service
metadata:
  name: flows
spec:
  selector:
    app: flows
  ports:
    - protocol: TCP
      port: 3400
      targetPort: 3400
  type: ClusterIP
