apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: movieguru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.REGION }}-docker.pkg.dev/{{ .Values.PROJECT_ID }}/movie-guru/frontend:{{ .Values.IMAGE.TAG }}"
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: movieguru
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
  namespace: movieguru
spec:
  parentRefs:
    - name: movieguru-gateway
      namespace: movieguru
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: frontend
          port: 8080
