# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemma-prompt
  namespace: movieguru
spec:
  selector:
    matchLabels:
      app: gemma-prompt
  template:
    metadata:
      labels:
        app: gemma-prompt
    spec:
      serviceAccountName: movieguru-sa
      nodeSelector:
       cloud.google.com/gke-nodepool: cpu-pool      
      containers:
        - name: gemma-prompt
          image: "{{ .Values.region }}-docker.pkg.dev/{{ .Values.projectID }}/movie-guru/gemma-prompt:{{ .Values.Image.tag }}"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "750m"
              memory: "2Gi"          
          env:
            - name: VLLM_URL
              value: "http://llm-service.movieguru.svc.cluster.local:8000/generate"          
            - name: CHAT_SERVER
              value: "http://server.movieguru.svc.cluster.local:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: gemma-prompt
  namespace: movieguru
spec:
  selector:
    app: gemma-prompt
  clusterIP: None
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gemma-prompt
  namespace: movieguru
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gemma-prompt
  minReplicas: {{ .Values.GemmaPrompt.minReplicas }}
  maxReplicas: 25
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50