# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-server
  namespace: movieguru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-test-server
  template:
    metadata:
      labels:
        app: load-test-server
    spec:
      serviceAccountName: movieguru-sa
      containers:
      - image: fortio/fortio
        imagePullPolicy: Always
        name: load-test-server
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
        args:
        - load
        - -t
        - "0" #run forever
        - -qps
        - "2"
        - -quiet
        - -keepalive
        - -allow-initial-errors
        - http://server.movieguru.svc.cluster.local:8080/
---
apiVersion: v1
kind: Service
metadata:
  name: load-test-server
  namespace: movieguru
  labels:
    app: load-test-server
spec:
  clusterIP: None
  selector:
    app: load-test-server
