
services:
  mock:
    build: ./js/mock-user
    ports:
      - "3402:3400"
      - "4002:4000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
      - LOCATION=europe-west4
    volumes:
      - ./.key.json:/key.json  
  