version: '3.8'
services:
  vite-app:
    build:
      context: ./frontend
      args:
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_GCP_PROJECT_ID: ${VITE_GCP_PROJECT_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
        VITE_FIREBASE_MESSAGING_SENDERID: ${VITE_FIREBASE_MESSAGING_SENDERID}
        VITE_FIREBASE_APPID: ${VITE_FIREBASE_APPID}
        VITE_CHAT_SERVER_URL: ${VITE_CHAT_SERVER_URL}
    ports:
      - "4000:4000"
   