export FIREBASE_API_KEY="some value"
export FIREBASE_AUTH_DOMAIN="some value"
export FIREBASE_GCP_ID="some value"
export FIREBASE_STORAGE_BUCKET="some value"
export FIREBASE_MESSAGING_SENDERID="some value"
export FIREBASE_APPID="some value"
export GATEWAY_IP="the gateway's IP address"
export SERVER_URL="http://${GATEWAY_IP}"
