export VITE_FIREBASE_API_KEY="some value"
export VITE_FIREBASE_AUTH_DOMAIN="some value"
export VITE_FIREBASE_GCP_ID="some value"
export VITE_FIREBASE_STORAGE_BUCKET="some value"
export VITE_FIREBASE_MESSAGING_SENDERID="some value"
export VITE_FIREBASE_APPID="some value"
export VITE_CHAT_SERVER_URL="some value"
export GATEWAY_IP="the gateway's IP address"
