# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockuser
  namespace: mockuser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockuser
  template:
    metadata:
      labels:
        app: mockuser
    spec:
      serviceAccountName: mockuser-sa
      containers:
      - name: mock-user-js
        image: "{{ .Values.REGION }}-docker.pkg.dev/{{ .Values.PROJECT_ID }}/movie-guru/mockuser:{{ .Values.IMAGE.TAG }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3400
        env:
        - name: PROJECT_ID
          value: {{ .Values.PROJECT_ID }}
        - name: LOCATION
          value: {{ .Values.REGION }}
---
apiVersion: v1
kind: Service
metadata:
  name: mockuser-service
  namespace: mockuser
spec:
  selector:
    app: mockuser
  ports:
  - protocol: TCP
    port: 80  # The port users will access the frontend on
    targetPort: 3400 # The port your frontend container is listening on
  type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: server-route
  namespace: movieguru
spec:
  parentRefs:
    - name: movieguru-gateway
      namespace: movieguru
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/mockuser"
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/"
      backendRefs:
        - name: mockuser
          port: 8080