apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockuser
  namespace: mockuser
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mockuser
  template:
    metadata:
      labels:
        app: mockuser
    spec:
      serviceAccountName: mockuser-sa
      containers:
      - name: mock-user-js
        image: "{{ .Values.REGION }}-docker.pkg.dev/{{ .Values.PROJECT_ID }}/movie-guru/mockuser:{{ .Values.IMAGE.TAG }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3400
        env:
        - name: PROJECT_ID
          value: {{ .Values.PROJECT_ID }}
        - name: LOCATION
          value: us-west-1
---
apiVersion: v1
kind: Service
metadata:
  name: mockuser
  namespace: mockuser
spec:
  selector:
    app: mockuser
  ports:
  - protocol: TCP
    port: 80  # The port users will access the frontend on
    targetPort: 3400 # The port your frontend container is listening on
  type: ClusterIP
