# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 7200s # 2hr
tags:
  - ci

steps:
# - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#   id: "download-config"
#   entrypoint: "bash"
#   args:
#     - "-c"
#     - |
#       gsutil cp gs://fb-webapp-$PROJECT_ID/app-config.json /workspace/app-config.json

# Not needed
# - name: "ubuntu"
#   id: "set-env-vars"
#   entrypoint: "bash"
#   args:
#     - "-c"
#     - |
#       apt-get update && apt-get install -y jq
#       export $(jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]' /workspace/app-config.json)
      
#       # Store variables as Cloud Build substitutions
#       echo "export _VITE_FIREBASE_API_KEY=$apiKey" >> /workspace/env-vars.txt
#       echo "export _VITE_FIREBASE_AUTH_DOMAIN=$authDomain" >> /workspace/env-vars.txt
#       echo "export _VITE_GCP_PROJECT_ID=${_PROJECT_ID}" >> /workspace/env-vars.txt
#       echo "export _VITE_FIREBASE_STORAGE_BUCKET=$storageBucket" >> /workspace/env-vars.txt
#       echo "export _VITE_FIREBASE_MESSAGING_SENDERID=$messagingSenderId" >> /workspace/env-vars.txt
#       echo "export _VITE_FIREBASE_APPID=$appId" >> /workspace/env-vars.txt
#       echo "export _VITE_CHAT_SERVER_URL=http://${gatewayIP}/server:4000" >> /workspace/env-vars.txt 
#       echo "workspace file: $(cat /workspace/env-vars.txt)"

- name: "gcr.io/cloud-builders/docker"
  id: "build-frontend"
  dir: './frontend'
  entrypoint: "bash"
  args:
    - "-c"
    - |
      docker build \
        --build-arg VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY \
        --build-arg VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN \
        --build-arg VITE_GCP_PROJECT_ID=$_VITE_GCP_PROJECT_ID \
        --build-arg VITE_FIREBASE_STORAGE_BUCKET=$_VITE_FIREBASE_STORAGE_BUCKET \
        --build-arg VITE_FIREBASE_MESSAGING_SENDERID=$_VITE_FIREBASE_MESSAGING_SENDERID \
        --build-arg VITE_FIREBASE_APPID=$_VITE_FIREBASE_APPID \
        --build-arg VITE_CHAT_SERVER_URL=$_VITE_CHAT_SERVER_URL \
        -t "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/frontend:${_SHORT_SHA}" \
        -t "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/frontend:latest" \
        --cache-from "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/frontend:latest" \
        .

- name: 'gcr.io/cloud-builders/docker'
  id: "push-frontend-image"
  entrypoint: "sh"
  args:
    - -xe 
    - -c
    - |
      docker push '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/frontend:${_SHORT_SHA}' && \
      docker push '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/frontend:latest'
- name: 'gcr.io/cloud-builders/docker'
  id: "build-server-image"
  dir: './chat_server_go'
  entrypoint: "sh"
  args:
    - -xe 
    - -c
    - |
      docker build \
         -t "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/chatserver:${_SHORT_SHA}" \
         -t "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/chatserver:latest" \
         --cache-from "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/chatserver:latest" \
         .
- name: 'gcr.io/cloud-builders/docker'
  id: "push-server-image"
  entrypoint: "sh"
  args:
    - -xe 
    - -c
    - |
      docker push '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/chatserver:${_SHORT_SHA}' && \
      docker push '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/chatserver:latest'

- name: 'gcr.io/cloud-builders/docker'
  id: "build-flows-image"
  dir: './js/flows'
  entrypoint: "sh"
  args:
    - -xe 
    - -c
    - |
      docker build \
         -t "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/flows:${_SHORT_SHA}" \
         -t "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/flows:latest" \
         --cache-from "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/flows:latest" \
         .
- name: 'gcr.io/cloud-builders/docker'
  id: "push-flows-image"
  entrypoint: "sh"
  args:
    - -xe 
    - -c
    - |
      docker push '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/flows:${_SHORT_SHA}'  && \
      docker push '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/flows:latest'

- name: 'gcr.io/cloud-builders/docker'
  id: "build-db-image"
  dir: './pgvector'
  entrypoint: "sh"
  args:
    - -xe 
    - -c
    - |
      docker build \
         -t "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/db:${_SHORT_SHA}" \
         -t "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/db:latest" \
         --cache-from "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/db:latest" \
         .

- name: 'gcr.io/cloud-builders/docker'
  id: "push-db-image"
  entrypoint: "sh"
  args:
    - -xe 
    - -c
    - |
      docker push '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/db:${_SHORT_SHA}' && \
      docker push '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/db:latest'

- name: 'gcr.io/cloud-builders/docker'
  id: "build-db-init-image"
  dir: './pgvector'
  entrypoint: "sh"
  args:
    - -xe 
    - -c
    - |
      docker build \
         -t "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/db-init:${_SHORT_SHA}" \
         -t "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/db-init:latest" \
         --cache-from "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/db-init:latest" \
         -f Dockerfile.init \
         .

- name: 'gcr.io/cloud-builders/docker'
  id: "push-db-init-image"
  entrypoint: "sh"
  args:
    - -xe 
    - -c
    - |
      docker push '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/db-init:${_SHORT_SHA}' && \
      docker push '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/db-init:latest'

- name: 'gcr.io/cloud-builders/docker'
  id: "build-indexer-image"
  dir: './indexer'
  entrypoint: "sh"
  args:
    - -xe 
    - -c
    - |
      docker build \
         -t "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/indexer:${_SHORT_SHA}" \
         -t "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/indexer:latest" \
         --cache-from "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/indexer:latest" \
         -f Dockerfile.init \
         .

- name: 'gcr.io/cloud-builders/docker'
  id: "push-indexer-image"
  entrypoint: "sh"
  args:
    - -xe 
    - -c
    - |
      docker push '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/indexer:${_SHORT_SHA}' && \
      docker push '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/indexer:latest'

- name: 'gcr.io/cloud-builders/docker'
  id: "tag-webserver-image"
  entrypoint: "sh"
  args:
    - -xe 
    - -c
    - |
      docker tag \
         ghcr.io/static-web-server/static-web-server:2.36 \
         "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/static-web-server:2.36"

- name: 'gcr.io/cloud-builders/docker'
  id: "push-webserver-image"
  entrypoint: "sh"
  args:
    - -xe 
    - -c
    - |
      docker push '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/movie-guru/static-web-server:2.36

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE
  dynamic_substitutions: true