apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-sa
  namespace: otel-collector
  annotations:
    iam.gke.io/gcp-service-account: movie-guru-chat-server-sa@{{ .Values.}}.iam.gserviceaccount.com 